### PR TITLE
Added initial Renesas Cortex-R52 support.

### PR DESCRIPTION
**Pull request by RICCIARDI-Adrien**

### CODE REVIEW

**Review by jlbirccyn — COMMENTED** [review]
There is no file listed in the object ```PLATFORM_FILES``` of ```templates/config/cortex-a-r/armv8/config.oil```. Is it normal or is it a mistake ?

**Comment by RICCIARDI-Adrien** [comment]
Yes, this is normal. ARMV8-generic files will be added here when a new ARMV8 machine will be supported.

**Review by jlbirccyn — APPROVED** [review]

**Comment by jlbirccyn** [comment]
Maybe add the new target in the general README

**Comment by jlbirccyn** [comment]
Ok to merge :+1:

**Pull request merged**
